# Dockerfile.alpine
FROM mhart/alpine-node:8.9.1

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies modules
COPY package.json /usr/src/app/
RUN npm cache clean --force
RUN npm install --registry=http://192.168.1.3:4873 && rm -f package.json
