# Dockerfile.alpine
FROM mhart/alpine-node:8.4.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies modules
COPY package.json /usr/src/app/
RUN npm cache clean --force
RUN npm install --registry=https://registry.npm.taobao.org && rm -f package.json
